/**
 * Intelligence Fusion Engine — External × Internal = Opportunity Intelligence
 * ========================================================================
 *
 * The FUSION equation:
 *   External Intelligence (signals, evidence, company data)
 *   × Internal Intelligence (capabilities, case studies, proof points)
 *   = Opportunity Intelligence (what to sell, who to target, what to say)
 *
 * This engine is called AFTER both enrichment and capability matching.
 * It doesn't re-query LLMs — it uses already-persisted data to create
 * FusionResult records with reasoning chains for explainability.
 *
 * COST OPTIMIZATION: This engine is PURE LOGIC — no AI calls.
 * All intelligence was already generated by the pipeline.
 */

import { db } from '@/lib/db';

// ── Types ──

export interface FusionInput {
  companyId: string;
  signalIds?: string[];     // specific signals to fuse (optional — uses all if empty)
  capabilityIds?: string[]; // specific capabilities to fuse (optional — uses all matches if empty)
}

export interface FusionOutput {
  success: boolean;
  companyId: string;
  fusionResults: FusionResultItem[];
  totalFusions: number;
  highConfidenceFusions: number;
  error: string | null;
}

interface FusionResultItem {
  id: string;
  fusionType: string;
  fusionScore: number;
  businessProblem: string | null;
  recommendedCapability: string | null;
  relevantCaseStudy: string | null;
  proofPoints: string[];
  reasoningChain: Array<{ step: string; input: string; output: string; confidence: number }>;
  confidenceScore: number;
  evidenceStrength: number;
}

// ── Fusion Engine ──

export const FusionEngine = {
  /**
   * Run intelligence fusion for a company.
   * Combines signals + capability matches + evidence into FusionResult records.
   */
  async fuse(input: FusionInput): Promise<FusionOutput> {
    try {
      const { companyId } = input;

      // Load all intelligence data for this company
      const company = await db.company.findUnique({
        where: { id: companyId },
        include: {
          signals: { where: { status: { in: ['active', 'validated', 'aging'] } }, take: 10 },
          signalCapabilityMatches: { take: 20, orderBy: { matchScore: 'desc' }, include: { capability: true, signal: true } },
          evidence: { where: { status: 'active' }, take: 10 },
          opportunityRecommendations: { take: 10, orderBy: { opportunityScore: 'desc' } },
        },
      });

      if (!company) {
        return { success: false, companyId, fusionResults: [], totalFusions: 0, highConfidenceFusions: 0, error: 'Company not found' };
      }

      // Filter by specific IDs if provided
      let signals = company.signals;
      let matches = company.signalCapabilityMatches;

      if (input.signalIds?.length) {
        signals = signals.filter(s => input.signalIds!.includes(s.id));
      }
      if (input.capabilityIds?.length) {
        matches = matches.filter(m => input.capabilityIds!.includes(m.capabilityId));
      }

      const results: FusionResultItem[] = [];

      // ── Fusion Type 1: Signal → Capability Fusion ──
      // For each signal-capability match, create a fusion result with reasoning chain
      for (const match of matches) {
        const signal = match.signal;
        const capability = match.capability;
        if (!signal || !capability) continue;

        const evidenceForSignal = company.evidence.filter(e =>
          e.extractedField === 'signal_intelligence' || e.snippet.toLowerCase().includes(signal.title.toLowerCase().slice(0, 30))
        );

        const relatedOpp = company.opportunityRecommendations.find(o =>
          o.capabilityMatchId === match.id || o.signalId === match.signalId
        );

        // Calculate fusion score
        const signalStrength = signal.confidence || 0.7;
        const capabilityFit = match.matchScore;
        const evidenceMultiplier = evidenceForSignal.length > 0 ? 1.0 : 0.7;
        const fusionScore = Math.min(1, (signalStrength * 0.4 + capabilityFit * 0.4 + evidenceMultiplier * 0.2));

        // Build reasoning chain for explainability
        const reasoningChain = [
          {
            step: 'signal_detected',
            input: `Signal: ${signal.signalType} — ${signal.title}`,
            output: `Severity: ${signal.severity}, Impact: ${signal.impact}, Confidence: ${signal.confidence}`,
            confidence: signal.confidence || 0.7,
          },
          {
            step: 'capability_matched',
            input: `Capability: ${capability.title} (${capability.category})`,
            output: `Match score: ${match.matchScore}, Problem: ${match.businessProblem || 'N/A'}`,
            confidence: match.matchScore,
          },
          {
            step: 'evidence_assessed',
            input: `${evidenceForSignal.length} evidence records found`,
            output: evidenceForSignal.length > 0
              ? `Evidence: ${evidenceForSignal.map(e => e.sourceName).join(', ')}`
              : 'No direct evidence — relying on signal confidence',
            confidence: evidenceForSignal.length > 0 ? 0.9 : 0.5,
          },
          {
            step: 'fusion_scored',
            input: `Signal(${signalStrength}) × Capability(${capabilityFit}) × Evidence(${evidenceMultiplier})`,
            output: `Fusion Score: ${Math.round(fusionScore * 100)}%`,
            confidence: fusionScore,
          },
        ];

        // Find relevant case study
        const caseStudies = await db.capabilityAsset.findMany({
          where: {
            isActive: true,
            category: 'case_study',
            OR: [
              { serviceLine: capability.serviceLine },
              { industry: company.industry || undefined },
            ],
          },
          take: 1,
        });

        const result: FusionResultItem = {
          id: '', // will be set by DB
          fusionType: 'signal_capability',
          fusionScore,
          businessProblem: match.businessProblem || signal.description?.slice(0, 300) || null,
          recommendedCapability: capability.title,
          relevantCaseStudy: caseStudies[0]?.title || null,
          proofPoints: [
            ...(match.expectedOutcome ? [match.expectedOutcome] : []),
            ...(match.salesAngle ? [match.salesAngle] : []),
            ...(relatedOpp ? [relatedOpp.whyNow || ''] : []),
          ].filter(Boolean),
          reasoningChain,
          confidenceScore: fusionScore,
          evidenceStrength: evidenceForSignal.length > 0 ? Math.min(1, evidenceForSignal.length * 0.3) : 0,
        };

        // Persist to DB
        const persisted = await db.fusionResult.create({
          data: {
            companyId,
            signalIds: JSON.stringify([signal.id]),
            capabilityIds: JSON.stringify([capability.id]),
            evidenceIds: JSON.stringify(evidenceForSignal.map(e => e.id)),
            fusionType: result.fusionType,
            fusionScore: result.fusionScore,
            businessProblem: result.businessProblem,
            recommendedCapability: result.recommendedCapability,
            relevantCaseStudy: result.relevantCaseStudy,
            proofPoints: JSON.stringify(result.proofPoints),
            reasoningChain: JSON.stringify(result.reasoningChain),
            confidenceScore: result.confidenceScore,
            evidenceStrength: result.evidenceStrength,
          },
        });

        result.id = persisted.id;
        results.push(result);
      }

      // ── Fusion Type 2: Full Company Fusion ──
      // Aggregate all signals and matches into a single high-level fusion
      if (results.length > 0) {
        const avgScore = results.reduce((a, r) => a + r.fusionScore, 0) / results.length;
        const topCapability = results.sort((a, b) => b.fusionScore - a.fusionScore)[0]?.recommendedCapability || null;
        const allProblems = [...new Set(results.map(r => r.businessProblem).filter(Boolean))];
        const allProofPoints = [...new Set(results.flatMap(r => r.proofPoints))];

        const fullFusion = await db.fusionResult.create({
          data: {
            companyId,
            signalIds: JSON.stringify(signals.map(s => s.id)),
            capabilityIds: JSON.stringify(matches.map(m => m.capabilityId)),
            evidenceIds: JSON.stringify(company.evidence.map(e => e.id)),
            fusionType: 'full_fusion',
            fusionScore: avgScore,
            businessProblem: allProblems[0] || null,
            recommendedCapability: topCapability,
            proofPoints: JSON.stringify(allProofPoints),
            reasoningChain: JSON.stringify([
              { step: 'aggregation', input: `${results.length} signal-capability fusions`, output: `Average fusion score: ${Math.round(avgScore * 100)}%`, confidence: avgScore },
              { step: 'top_recommendation', input: 'Best match selected', output: `Position: ${topCapability || 'N/A'}`, confidence: avgScore },
            ]),
            confidenceScore: avgScore,
            evidenceStrength: Math.min(1, company.evidence.length * 0.1),
          },
        });

        results.unshift({
          id: fullFusion.id,
          fusionType: 'full_fusion',
          fusionScore: avgScore,
          businessProblem: allProblems[0] || null,
          recommendedCapability: topCapability,
          relevantCaseStudy: results.find(r => r.relevantCaseStudy)?.relevantCaseStudy || null,
          proofPoints: allProofPoints,
          reasoningChain: [{ step: 'full_fusion', input: `${results.length - 1} sub-fusions`, output: `Score: ${Math.round(avgScore * 100)}%`, confidence: avgScore }],
          confidenceScore: avgScore,
          evidenceStrength: Math.min(1, company.evidence.length * 0.1),
        });
      }

      const highConfidence = results.filter(r => r.fusionScore >= 0.6).length;

      return {
        success: true,
        companyId,
        fusionResults: results,
        totalFusions: results.length,
        highConfidenceFusions: highConfidence,
        error: null,
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, companyId: input.companyId, fusionResults: [], totalFusions: 0, highConfidenceFusions: 0, error: msg };
    }
  },

  /**
   * Get fusion results for a company.
   */
  async getFusions(companyId: string): Promise<FusionResultItem[]> {
    const records = await db.fusionResult.findMany({
      where: { companyId, status: 'active' },
      orderBy: { fusionScore: 'desc' },
      take: 20,
    });

    return records.map(r => ({
      id: r.id,
      fusionType: r.fusionType,
      fusionScore: r.fusionScore,
      businessProblem: r.businessProblem,
      recommendedCapability: r.recommendedCapability,
      relevantCaseStudy: r.relevantCaseStudy,
      proofPoints: JSON.parse(r.proofPoints as string || '[]'),
      reasoningChain: JSON.parse(r.reasoningChain as string || '[]'),
      confidenceScore: r.confidenceScore,
      evidenceStrength: r.evidenceStrength,
    }));
  },
};
