// Mock data for demo mode (when no database is available on Vercel)

export const MOCK_USER = {
  id: 'demo-user-1',
  name: 'Ravi Shanker',
  email: 'ravi@deepmindq.com',
  role: 'admin',
  image: null,
  emailVerified: new Date().toISOString(),
  passwordHash: null,
  lastLoginAt: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}

export const MOCK_COMPANIES = [
  {
    id: 'comp-1',
    name: 'Acme Corp',
    domain: 'acmecorp.com',
    linkedinUrl: 'https://linkedin.com/company/acmecorp',
    website: 'https://acmecorp.com',
    industry: 'Technology',
    employeeSize: '500-1000',
    country: 'United States',
    location: 'San Francisco, CA',
    status: 'active',
    intelligenceScore: 87,
    dataFreshness: 'fresh',
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    contacts: [],
    opportunities: [],
    notes: [],
    timeline: [],
  },
  {
    id: 'comp-2',
    name: 'TechVentures Inc',
    domain: 'techventures.io',
    linkedinUrl: 'https://linkedin.com/company/techventures',
    website: 'https://techventures.io',
    industry: 'SaaS',
    employeeSize: '100-250',
    country: 'India',
    location: 'Bangalore, KA',
    status: 'new',
    intelligenceScore: 72,
    dataFreshness: 'fresh',
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    contacts: [],
    opportunities: [],
    notes: [],
    timeline: [],
  },
  {
    id: 'comp-3',
    name: 'Global Finance Solutions',
    domain: 'gfsolutions.com',
    linkedinUrl: null,
    website: 'https://gfsolutions.com',
    industry: 'Finance',
    employeeSize: '1000-5000',
    country: 'United Kingdom',
    location: 'London, UK',
    status: 'active',
    intelligenceScore: 91,
    dataFreshness: 'stale',
    lastUpdatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    contacts: [],
    opportunities: [],
    notes: [],
    timeline: [],
  },
  {
    id: 'comp-4',
    name: 'HealthTech Plus',
    domain: 'healthtechplus.com',
    linkedinUrl: 'https://linkedin.com/company/healthtechplus',
    website: 'https://healthtechplus.com',
    industry: 'Healthcare',
    employeeSize: '250-500',
    country: 'United States',
    location: 'Boston, MA',
    status: 'researching',
    intelligenceScore: 78,
    dataFreshness: 'fresh',
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    contacts: [],
    opportunities: [],
    notes: [],
    timeline: [],
  },
  {
    id: 'comp-5',
    name: 'GreenEnergy Corp',
    domain: 'greenenergy.co',
    linkedinUrl: null,
    website: 'https://greenenergy.co',
    industry: 'Energy',
    employeeSize: '50-100',
    country: 'Germany',
    location: 'Berlin, DE',
    status: 'new',
    intelligenceScore: 65,
    dataFreshness: 'unknown',
    lastUpdatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    contacts: [],
    opportunities: [],
    notes: [],
    timeline: [],
  },
  {
    id: 'comp-6',
    name: 'CloudScale Systems',
    domain: 'cloudscale.dev',
    linkedinUrl: 'https://linkedin.com/company/cloudscale',
    website: 'https://cloudscale.dev',
    industry: 'Cloud Computing',
    employeeSize: '1000-5000',
    country: 'United States',
    location: 'Seattle, WA',
    status: 'active',
    intelligenceScore: 93,
    dataFreshness: 'fresh',
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    contacts: [],
    opportunities: [],
    notes: [],
    timeline: [],
  },
]

export const MOCK_CONTACTS = [
  {
    id: 'cont-1',
    companyId: 'comp-1',
    name: 'Sarah Johnson',
    email: 'sarah@acmecorp.com',
    jobTitle: 'VP of Engineering',
    roleBucket: 'decision-maker',
    linkedinUrl: 'https://linkedin.com/in/sarahjohnson',
    phone: '+1 415-555-0101',
    location: 'San Francisco, CA',
    status: 'active',
    emailHealth: 'valid',
    emailHealthScore: 95,
    lastContactedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-2',
    companyId: 'comp-1',
    name: 'Mike Chen',
    email: 'mike.chen@acmecorp.com',
    jobTitle: 'CTO',
    roleBucket: 'decision-maker',
    linkedinUrl: 'https://linkedin.com/in/mikechen',
    phone: '+1 415-555-0102',
    location: 'San Francisco, CA',
    status: 'active',
    emailHealth: 'valid',
    emailHealthScore: 92,
    lastContactedAt: null,
    lastValidatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-3',
    companyId: 'comp-2',
    name: 'Priya Sharma',
    email: 'priya@techventures.io',
    jobTitle: 'Head of Product',
    roleBucket: 'influencer',
    linkedinUrl: 'https://linkedin.com/in/priyasharma',
    phone: '+91 80-555-0201',
    location: 'Bangalore, KA',
    status: 'new',
    emailHealth: 'valid',
    emailHealthScore: 88,
    lastContactedAt: null,
    lastValidatedAt: null,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-4',
    companyId: 'comp-3',
    name: 'James Wilson',
    email: 'j.wilson@gfsolutions.com',
    jobTitle: 'CFO',
    roleBucket: 'decision-maker',
    linkedinUrl: null,
    phone: '+44 20-555-0301',
    location: 'London, UK',
    status: 'active',
    emailHealth: 'valid',
    emailHealthScore: 90,
    lastContactedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    lastValidatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-5',
    companyId: 'comp-4',
    name: 'Dr. Emily Brown',
    email: 'emily.b@healthtechplus.com',
    jobTitle: 'Director of Innovation',
    roleBucket: 'champion',
    linkedinUrl: 'https://linkedin.com/in/emilybrown',
    phone: '+1 617-555-0401',
    location: 'Boston, MA',
    status: 'new',
    emailHealth: 'risky',
    emailHealthScore: 60,
    lastContactedAt: null,
    lastValidatedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cont-6',
    companyId: 'comp-6',
    name: 'David Park',
    email: 'david.park@cloudscale.dev',
    jobTitle: 'VP of Cloud Infrastructure',
    roleBucket: 'decision-maker',
    linkedinUrl: 'https://linkedin.com/in/davidpark',
    phone: '+1 206-555-0601',
    location: 'Seattle, WA',
    status: 'active',
    emailHealth: 'valid',
    emailHealthScore: 97,
    lastContactedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    lastValidatedAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_OPPORTUNITIES = [
  {
    id: 'opp-1',
    companyId: 'comp-1',
    title: 'Enterprise License Deal',
    description: 'Annual enterprise license for AI sales intelligence platform',
    targetContactId: 'cont-1',
    status: 'proposal-sent',
    nextAction: 'Follow up on proposal by Friday',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-2',
    companyId: 'comp-6',
    title: 'Cloud Integration Partnership',
    description: 'Strategic partnership for cloud-based CRM integration',
    targetContactId: 'cont-6',
    status: 'negotiation',
    nextAction: 'Schedule demo with engineering team',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'opp-3',
    companyId: 'comp-3',
    title: 'Financial Analytics Module',
    description: 'Custom analytics module for financial services clients',
    targetContactId: 'cont-4',
    status: 'researching',
    nextAction: 'Prepare industry-specific case study',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_TASKS = [
  {
    id: 'task-1',
    title: 'Follow up with Acme Corp',
    description: 'Send revised proposal to Sarah Johnson',
    status: 'pending',
    priority: 'high',
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    completedAt: null,
    companyId: 'comp-1',
    contactId: 'cont-1',
    assignedTo: 'demo-user-1',
    createdBy: 'demo-user-1',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'Research HealthTech Plus',
    description: 'Deep dive into their current tech stack',
    status: 'in-progress',
    priority: 'medium',
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    completedAt: null,
    companyId: 'comp-4',
    contactId: 'cont-5',
    assignedTo: 'demo-user-1',
    createdBy: 'demo-user-1',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    title: 'Prepare quarterly report',
    description: 'Compile sales metrics for Q2 review',
    status: 'completed',
    priority: 'low',
    dueDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    companyId: null,
    contactId: null,
    assignedTo: 'demo-user-1',
    createdBy: 'demo-user-1',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
]

export const MOCK_DRAFTS = [
  {
    id: 'draft-1',
    contactId: 'cont-1',
    subject: 'Re: Enterprise License Proposal',
    body: 'Hi Sarah,\n\nThank you for reviewing our proposal. I wanted to follow up on a few key points...',
    cta: 'Would you be available for a 30-minute call this Thursday?',
    serviceAngle: 'AI-Powered Sales Intelligence',
    matchScore: 94,
    confidenceScore: 89,
    status: 'draft',
    rejectReason: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'draft-2',
    contactId: 'cont-6',
    subject: 'Cloud Integration Partnership - Next Steps',
    body: 'Hi David,\n\nFollowing our great conversation last week about the cloud integration opportunity...',
    cta: 'Can we schedule a technical deep-dive for next week?',
    serviceAngle: 'Cloud CRM Integration',
    matchScore: 88,
    confidenceScore: 85,
    status: 'sent',
    rejectReason: null,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_CAPABILITY_DOCS = [
  {
    id: 'cap-1',
    title: 'AI Sales Intelligence Overview',
    docType: 'case-study',
    description: 'How AI transforms enterprise sales discovery and outreach',
    content: 'Our AI-powered platform enables sales teams to discover 10x more qualified leads...',
    fileName: 'ai-sales-intel.pdf',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cap-2',
    title: 'Email Deliverability Best Practices',
    docType: 'whitepaper',
    description: 'Technical guide to achieving 95%+ email deliverability',
    content: 'Email deliverability is a complex topic that requires attention to SPF, DKIM, and DMARC records...',
    fileName: 'deliverability-guide.pdf',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cap-3',
    title: 'Enterprise Integration Guide',
    docType: 'documentation',
    description: 'Step-by-step guide for integrating with Salesforce, HubSpot, and more',
    content: 'Our REST API supports seamless integration with all major CRM platforms...',
    fileName: 'integration-guide.pdf',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_PROMPT_TEMPLATES = [
  {
    id: 'pt-1',
    name: 'Cold Outreach - Executive',
    category: 'outreach',
    description: 'Personalized cold email for C-suite executives',
    systemPrompt: 'You are an expert B2B sales copywriter.',
    userPromptTemplate: 'Write a cold outreach email to {{name}} ({{title}} at {{company}}) about {{service}}.',
    variables: 'name,title,company,service',
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pt-2',
    name: 'Follow-Up - Post Demo',
    category: 'follow-up',
    description: 'Follow-up email after a product demonstration',
    systemPrompt: 'You are a helpful sales assistant.',
    userPromptTemplate: 'Write a follow-up email to {{name}} after our demo of {{product}}. Key points discussed: {{points}}.',
    variables: 'name,product,points',
    isBuiltIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Dashboard stats
export const MOCK_DASHBOARD_STATS = {
  totalCompanies: 247,
  totalContacts: 1843,
  activeOpportunities: 38,
  emailsSent: 156,
  avgIntelligenceScore: 82,
  conversionRate: 12.4,
  weeklyTrend: [
    { week: 'W1', companies: 12, contacts: 45, opportunities: 3 },
    { week: 'W2', companies: 18, contacts: 62, opportunities: 5 },
    { week: 'W3', companies: 15, contacts: 38, opportunities: 4 },
    { week: 'W4', companies: 22, contacts: 71, opportunities: 7 },
    { week: 'W5', companies: 28, contacts: 89, opportunities: 9 },
    { week: 'W6', companies: 32, contacts: 95, opportunities: 11 },
  ],
  statusBreakdown: [
    { name: 'Active', value: 45, color: '#059669' },
    { name: 'New', value: 28, color: '#2563EB' },
    { name: 'Researching', value: 15, color: '#D97706' },
    { name: 'Inactive', value: 12, color: '#9CA3AF' },
  ],
  industryBreakdown: [
    { name: 'Technology', value: 35 },
    { name: 'Finance', value: 20 },
    { name: 'Healthcare', value: 15 },
    { name: 'SaaS', value: 18 },
    { name: 'Other', value: 12 },
  ],
}