'use client'

import { useState, useRef, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import {
  ShieldCheck, AlertCircle, ShieldAlert, AlertTriangle, CheckCircle2, RefreshCw,
} from 'lucide-react'

/* ═══════════════════════════════════════════════════════════════
   Company Profile — Shared UI Components
   Extracted from company-profile-screen.tsx (Task 3.2)
   ═══════════════════════════════════════════════════════════════ */

type GovernanceStatus = 'verified' | 'needs_review' | 'failed' | 'not_evaluated' | null | undefined

export function GovernanceBadge({ status }: { status: GovernanceStatus }) {
  if (!status || status === 'not_evaluated') {
    return (
      <span className="inline-flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded-md bg-gray-100 text-gray-500 border border-gray-200">
        <span className="size-1.5 rounded-full bg-gray-400" /> Not Evaluated
      </span>
    )
  }
  if (status === 'verified') {
    return (
      <span className="inline-flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded-md bg-emerald-50 text-emerald-700 border border-emerald-200">
        <ShieldCheck className="size-3" /> Verified
      </span>
    )
  }
  if (status === 'needs_review') {
    return (
      <span className="inline-flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded-md bg-amber-50 text-amber-700 border border-amber-200">
        <AlertCircle className="size-3" /> Needs Review
      </span>
    )
  }
  return (
    <span className="inline-flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded-md bg-red-50 text-red-700 border border-red-200">
      <ShieldAlert className="size-3" /> Governance Failed
    </span>
  )
}

/** Evidence grounding bar — Design Bible §6.3 */
export function EvidenceGroundingBar({ warnings }: { warnings: string[] | undefined }) {
  const hasUnverified = warnings?.some(w => w.toLowerCase().includes('unverified') || w.toLowerCase().includes('hallucin'))
  if (!warnings || warnings.length === 0) {
    return (
      <div className="flex items-center gap-1.5 text-[10px] text-emerald-600 bg-emerald-50/60 border border-emerald-100 rounded-md px-2 py-1">
        <CheckCircle2 className="size-3" />
        Evidence grounded — no fabricated metrics
      </div>
    )
  }
  return (
    <div className="flex items-center gap-1.5 text-[10px] text-amber-600 bg-amber-50/60 border border-amber-100 rounded-md px-2 py-1">
      <AlertTriangle className="size-3" />
      Contains unverified claims — review recommended
    </div>
  )
}

/** AI Footer — Design Bible §6.4 */
export function AIFooter({ model, durationMs }: { model?: string; durationMs?: number }) {
  if (!model && !durationMs) return null
  return (
    <p className="text-[10px] text-gray-400 mt-2 italic">
      Generated by DeepMindQ{model ? ` · ${model}` : ''}{durationMs ? ` · ${(durationMs / 1000).toFixed(1)}s` : ''}
    </p>
  )
}

/** Section error state with retry — Design Bible §1.6 */
export function SectionError({ message, onRetry }: { message: string; onRetry: () => void }) {
  return (
    <div className="rounded-xl border border-red-200 bg-red-50/40 p-6 text-center">
      <AlertCircle className="size-6 text-red-400 mx-auto mb-2" />
      <p className="text-sm text-red-700 font-medium">{message}</p>
      <Button size="sm" variant="outline" className="mt-2 border-red-200 text-red-600 hover:bg-red-50 rounded-md text-xs" onClick={onRetry}>
        <RefreshCw className="size-3 mr-1" /> Retry
      </Button>
    </div>
  )
}

/** Narrative divider between Q sections — Design Bible §1.5 */
export function NarrativeDivider({ label, subtitle, color, transition }: { label: string; subtitle: string; color: string; transition?: string }) {
  const colorMap: Record<string, { text: string; icon: string; bg: string }> = {
    blue: { text: 'text-blue-700', icon: 'text-blue-500', bg: 'bg-blue-50' },
    violet: { text: 'text-violet-700', icon: 'text-violet-500', bg: 'bg-violet-50' },
    emerald: { text: 'text-emerald-700', icon: 'text-emerald-500', bg: 'bg-emerald-50' },
    amber: { text: 'text-amber-700', icon: 'text-amber-500', bg: 'bg-amber-50' },
    rose: { text: 'text-rose-700', icon: 'text-rose-500', bg: 'bg-rose-50' },
  }
  const c = colorMap[color] || colorMap.blue
  return (
    <div className="space-y-1.5 py-2">
      <div className="flex items-center gap-3">
        <div className="h-px flex-1 bg-gray-200" />
        <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full ${c.bg}`}>
          <p className={`text-xs font-bold uppercase tracking-wider ${c.text}`}>{label}</p>
          <span className="text-gray-300">·</span>
          <p className="text-[10px] text-gray-500">{subtitle}</p>
        </div>
        <div className="h-px flex-1 bg-gray-200" />
      </div>
      {transition && (
        <p className="text-center text-[11px] text-gray-400 italic">{transition}</p>
      )}
    </div>
  )
}

/** Progressive Disclosure Hook — lazy-RENDERS section when visible */
export function useSectionVisible(sectionId: string) {
  const ref = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect() } },
      { rootMargin: '200px 0px' }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [sectionId])

  return { ref, visible }
}
