import { db } from '@/lib/db';
import { NextResponse } from 'next/server';

/* ═══════════════════════════════════════════════════════════════════════════
   POST /api/seed/gold-standard
   
   Creates the Gold Standard Account — Microsoft Corporation.
   
   This account is designed to pass all 5 co-founder validation tests:
   1. 10-minute executive meeting test
   2. Evidence trust test
   3. Intelligence density test (high signal, low noise)
   4. Demo wow moment
   5. Phase B readiness
   
   Run once. Deletes existing Microsoft data if present (idempotent).
   ═══════════════════════════════════════════════════════════════════════════ */

const NOW = new Date();
const DAYS_AGO = (n: number) => new Date(NOW.getTime() - n * 86400000);

export async function POST() {
  try {
    // ── Clean up any existing Microsoft data ──
    const existing = await db.company.findFirst({
      where: { normalizedName: { contains: 'microsoft' } },
    });
    if (existing) {
      await db.companySignal.deleteMany({ where: { companyId: existing.id } });
      await db.evidence.deleteMany({ where: { companyId: existing.id } });
      await db.contact.deleteMany({ where: { companyId: existing.id } });
      await db.companyResearchCard.deleteMany({ where: { companyId: existing.id } });
      await db.company.delete({ where: { id: existing.id } });
    }

    // ── Also clean existing capabilities so we can create matching ones ──
    // Only delete our gold-standard ones by specific title pattern
    const goldCapTitles = [
      'Cloud Migration & Modernization',
      'AI & Machine Learning Platform',
      'Cybersecurity & Zero Trust Architecture',
      'Data Analytics & Business Intelligence',
      'Application Modernization',
      'DevOps & Platform Engineering',
      'Enterprise Integration Services',
      'Digital Workplace Transformation',
    ];
    await db.capabilityAsset.deleteMany({
      where: { title: { in: goldCapTitles } },
    });

    // ── 1. Create Company ──
    const batch = await db.importBatch.create({
      data: {
        fileName: 'enterprise_accounts_gold.csv',
        fileHash: 'sha256:gold-standard-seed',
        totalRows: 1,
        acceptedRows: 1,
        duplicateRows: 0,
        invalidRows: 0,
        questionableRows: 0,
        status: 'completed',
        mappingProfile: 'enterprise_gold_standard',
      },
    });

    const company = await db.company.create({
      data: {
        rawName: 'Microsoft Corporation',
        normalizedName: 'microsoft corporation',
        domain: 'microsoft.com',
        industry: 'Technology',
        sizeRange: '10000+',
        location: 'Redmond, WA',
        country: 'United States',
        website: 'https://microsoft.com',
        internalSummary: 'Global technology leader. Massive cloud (Azure) expansion, AI investment (OpenAI partnership), and ongoing security transformation create significant engagement opportunities.',
        status: 'active',
        lifecycleStage: 'qualification',
        intelligenceScore: 92,
        engagementScore: 65,
        lastEnrichedAt: DAYS_AGO(1),
        lastActivityAt: DAYS_AGO(2),
        source: 'manual',
        assignedTo: 'sarah.chen',
      },
    });

    // ── 2. Create Research Card with rich tech data ──
    await db.companyResearchCard.create({
      data: {
        companyId: company.id,
        businessOverview: 'Microsoft Corporation is a global technology company operating in cloud computing (Azure), productivity software (Microsoft 365), AI (Copilot/OpenAI), gaming (Xbox/Activision), and enterprise services. FY2024 revenue exceeded $230B with Azure growing 29% YoY.',
        techLandscape: 'Azure, Kubernetes, Docker, React, TypeScript, Python, .NET, SQL Server, Cosmos DB, Power BI, Semantic Kernel, OpenAI GPT-4, Copilot Stack, Terraform, GitHub Actions, Defender for Cloud, Active Directory, Dynamics 365, Teams, SharePoint',
        potentialChallenges: 'Competitive pressure from AWS and Google Cloud. Integration complexity across acquired properties (Activision, Nuance). Regulatory scrutiny in EU and Asia. Security posture under constant threat.',
        possibleOpportunities: 'AI platform services demand. Copilot enterprise adoption. Azure hybrid cloud expansion. Security transformation projects. Data platform modernization. Developer tooling partnerships.',
        relevantServices: 'Cloud migration, AI/ML platform engineering, cybersecurity assessment, data analytics, application modernization, DevOps transformation',
        keyDecisionMakers: 'Satya Nadella (CEO), Judson Althoff (EVP CCO), Scott Guthrie (EVP Azure), Rajesh Jha (EVP M365), Charlie Bell (EVP Security)',
        revenue: '$230B+',
        employeeCount: '221,000+',
        fundingStage: 'public',
        techStack: JSON.stringify(['Azure', 'Kubernetes', 'Docker', 'React', 'TypeScript', 'Python', '.NET', 'SQL Server', 'Cosmos DB', 'Power BI', 'Terraform', 'GitHub Actions']),
        enrichmentSource: 'Gold Standard Seed',
        enrichmentDate: DAYS_AGO(1),
        strategicPriorities: JSON.stringify([
          { priority: 'AI-first strategy', description: 'Embedding AI across all products via Copilot and Azure OpenAI', evidence: 'FY2024 earnings call, multiple press releases', confidence: 0.95 },
          { priority: 'Cloud growth acceleration', description: 'Azure targeting 40%+ growth in AI services segment', evidence: 'Q4 earnings report, analyst coverage', confidence: 0.9 },
          { priority: 'Security transformation', description: 'Zero Trust architecture deployment across all product lines', evidence: 'Microsoft Security blog, RSA Conference keynote', confidence: 0.85 },
        ]),
        businessProblems: JSON.stringify(['multi-cloud integration complexity', 'AI governance and compliance', 'legacy system modernization', 'data platform unification', 'security threat landscape expansion']),
        transformationAreas: JSON.stringify(['AI integration across product lines', 'hybrid cloud optimization', 'zero trust security implementation', 'data mesh architecture', 'developer experience modernization']),
        technologyThemes: JSON.stringify(['generative AI', 'large language models', 'cloud-native architecture', 'zero trust security', 'observability platform', 'edge computing', 'sustainability tech']),
      },
    });

    // ── 3. Create Signals across all 4 categories ──
    const signals = await Promise.all([
      // TECHNOLOGY SIGNALS (3)
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'tech_change',
          title: 'Microsoft launches Azure AI Studio for enterprise generative AI development',
          description: 'Azure AI Studio provides a unified platform for building, testing, and deploying generative AI applications with integrated OpenAI models, RAG pipelines, and enterprise-grade security.',
          source: 'Microsoft Azure Blog',
          sourceUrl: 'https://azure.microsoft.com/en-us/blog/azure-ai-studio-launch',
          severity: 'critical',
          impact: 'high',
          signalDate: DAYS_AGO(3),
          confidence: 0.95,
          sourceQuality: 'premium',
          businessImpact: 'High — signals $500M+ AI services budget allocation and partner ecosystem demand',
          recommendedAction: 'Position AI platform capabilities within 14 days to align with Azure AI Studio launch momentum',
          timingWindow: 'within_14_days',
          meaningCategory: 'vendor_evaluation',
          status: 'active',
        },
      }),
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'tech_change',
          title: 'Microsoft adopts Kubernetes-based microservices architecture for Teams and Office',
          description: 'Migrating from monolithic architecture to Kubernetes-based microservices, enabling independent scaling and deployment across Teams, SharePoint, and OneDrive.',
          source: 'Microsoft Engineering Blog',
          sourceUrl: 'https://devblogs.microsoft.com/engineering/teams-microservices',
          severity: 'high',
          impact: 'high',
          signalDate: DAYS_AGO(8),
          confidence: 0.9,
          sourceQuality: 'premium',
          businessImpact: 'High — indicates cloud-native maturity and container orchestration expertise creating partnership opportunities',
          recommendedAction: 'Engage with container platform and DevOps capabilities within 30 days',
          timingWindow: 'within_30_days',
          meaningCategory: 'tech_dissatisfaction',
          status: 'active',
        },
      }),
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'tech_change',
          title: 'Microsoft Terraform provider v3.0 released with Azure governance enhancements',
          description: 'New provider version includes policy-as-code integration, drift detection, and multi-subscription management capabilities for Azure infrastructure.',
          source: 'GitHub - Microsoft Azure Terraform Provider',
          sourceUrl: 'https://github.com/hashicorp/terraform-provider-azurerm/releases/v3.0',
          severity: 'medium',
          impact: 'medium',
          signalDate: DAYS_AGO(15),
          confidence: 0.85,
          sourceQuality: 'standard',
          businessImpact: 'Medium — signals Infrastructure-as-code maturity and governance automation needs',
          recommendedAction: 'Monitor for cloud governance and IaC service opportunities',
          timingWindow: 'within_90_days',
          meaningCategory: 'growth_pressure',
          status: 'active',
        },
      }),

      // BUSINESS SIGNALS (3)
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'funding',
          title: 'Microsoft approves $10B Azure AI infrastructure expansion for FY2025',
          description: 'Board authorization for $10B capital expenditure to expand Azure AI compute infrastructure across 15 new data center regions by end of FY2025.',
          source: 'Microsoft Investor Relations',
          sourceUrl: 'https://www.microsoft.com/en-us/investor',
          severity: 'critical',
          impact: 'high',
          signalDate: DAYS_AGO(5),
          confidence: 0.95,
          sourceQuality: 'premium',
          businessImpact: 'Critical — $10B investment signals massive cloud growth and partnership appetite for infrastructure services',
          recommendedAction: 'Engage infrastructure and data center capabilities team within 7 days',
          timingWindow: 'within_7_days',
          meaningCategory: 'budget_available',
          status: 'active',
        },
      }),
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'expansion',
          title: 'Microsoft opens new Azure regions in São Paulo and Johannesburg',
          description: 'Expanding Azure presence to Latin America and Africa with new data center regions, targeting enterprise and government customers in emerging markets.',
          source: 'Microsoft News Center',
          sourceUrl: 'https://news.microsoft.com/azure-regions-expansion',
          severity: 'high',
          impact: 'high',
          signalDate: DAYS_AGO(12),
          confidence: 0.88,
          sourceQuality: 'premium',
          businessImpact: 'High — geographic expansion signals localization and compliance requirements creating regional service opportunities',
          recommendedAction: 'Position regional capabilities and compliance expertise within 30 days',
          timingWindow: 'within_30_days',
          meaningCategory: 'growth_pressure',
          status: 'active',
        },
      }),
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'partnership',
          title: 'Microsoft and SAP deepen strategic partnership on cloud ERP migration',
          description: 'Expanded RISE with SAP program integration with Azure, targeting 500+ joint enterprise customers for ERP cloud migration in next 18 months.',
          source: 'SAP News',
          sourceUrl: 'https://news.sap.com/microsoft-sap-partnership',
          severity: 'high',
          impact: 'high',
          signalDate: DAYS_AGO(18),
          confidence: 0.85,
          sourceQuality: 'premium',
          businessImpact: 'High — signals ERP modernization wave and integration partnership demand',
          recommendedAction: 'Position cloud migration and integration capabilities for SAP-on-Azure within 30 days',
          timingWindow: 'within_30_days',
          meaningCategory: 'vendor_evaluation',
          status: 'active',
        },
      }),

      // EXTERNAL SIGNALS (3)
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'leadership_change',
          title: 'Satya Nadella restructures engineering divisions under new CTO Rajesh Jha',
          description: 'Major engineering reorganization consolidating Windows, Office, and Azure engineering under unified technology leadership, signaling deeper product integration roadmap.',
          source: 'Reuters',
          sourceUrl: 'https://reuters.com/technology/microsoft-restructuring',
          severity: 'critical',
          impact: 'high',
          signalDate: DAYS_AGO(2),
          confidence: 0.92,
          sourceQuality: 'premium',
          businessImpact: 'High — leadership restructuring signals strategic direction shift and new vendor evaluation cycles',
          recommendedAction: 'Monitor for new technology partnerships and refresh engagement strategy within 30 days',
          timingWindow: 'within_30_days',
          meaningCategory: 'leadership_openness',
          status: 'active',
        },
      }),
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'news',
          title: 'Gartner names Microsoft a Leader in Cloud AI Developer Services Magic Quadrant',
          description: 'Microsoft positioned as a Leader for the 3rd consecutive year in Gartner Magic Quadrant for Cloud AI Developer Services, recognized for Azure AI completeness of vision.',
          source: 'Gartner',
          sourceUrl: 'https://gartner.com/reviews/microsoft-cloud-ai',
          severity: 'medium',
          impact: 'medium',
          signalDate: DAYS_AGO(20),
          confidence: 0.8,
          sourceQuality: 'premium',
          businessImpact: 'Medium — industry recognition validates AI investment trajectory and competitive positioning',
          recommendedAction: 'Reference in engagement materials and analyst-aligned positioning',
          timingWindow: 'ongoing',
          meaningCategory: 'growth_pressure',
          status: 'active',
        },
      }),
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'mention',
          title: 'Microsoft Copilot adoption reaches 60% of Fortune 500 companies',
          description: 'Enterprise Copilot adoption accelerating with 60% of Fortune 500 now using at least one Copilot product, signaling mainstream enterprise AI acceptance.',
          source: 'Bloomberg',
          sourceUrl: 'https://bloomberg.com/microsoft-copilot-enterprise-adoption',
          severity: 'high',
          impact: 'high',
          signalDate: DAYS_AGO(7),
          confidence: 0.88,
          sourceQuality: 'premium',
          businessImpact: 'High — rapid AI adoption creates services demand for implementation, customization, and training',
          recommendedAction: 'Position AI implementation and Copilot integration services within 14 days',
          timingWindow: 'within_14_days',
          meaningCategory: 'growth_pressure',
          status: 'active',
        },
      }),

      // RELATIONSHIP SIGNALS (2)
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'hiring',
          title: 'Microsoft hires 500+ AI engineers for Azure AI platform team',
          description: 'Major hiring surge for Azure AI platform, including ML engineers, data scientists, and AI product managers, based in Redmond and San Francisco.',
          source: 'LinkedIn Jobs + Microsoft Careers',
          sourceUrl: 'https://careers.microsoft.com/us/en/jobs',
          severity: 'high',
          impact: 'high',
          signalDate: DAYS_AGO(10),
          confidence: 0.85,
          sourceQuality: 'standard',
          businessImpact: 'High — massive AI hiring signals platform scaling demand and potential talent competition',
          recommendedAction: 'Identify hiring manager contacts and engage with AI platform staffing support',
          timingWindow: 'within_30_days',
          meaningCategory: 'budget_available',
          status: 'active',
        },
      }),
      db.companySignal.create({
        data: {
          companyId: company.id,
          signalType: 'hiring',
          title: 'Microsoft opening new cybersecurity center of excellence in Tel Aviv',
          description: 'Establishing a dedicated cybersecurity CoE in Israel to strengthen Microsoft Defender product line and expand zero trust architecture capabilities.',
          source: 'TechCrunch',
          sourceUrl: 'https://techcrunch.com/microsoft-cybersecurity-israel',
          severity: 'high',
          impact: 'medium',
          signalDate: DAYS_AGO(14),
          confidence: 0.82,
          sourceQuality: 'standard',
          businessImpact: 'Medium — signals security investment priority and potential partnership with Israeli security ecosystem',
          recommendedAction: 'Monitor for security partnership opportunities and engage regional security contacts',
          timingWindow: 'within_90_days',
          meaningCategory: 'leadership_openness',
          status: 'active',
        },
      }),
    ]);

    // ── 4. Create Contacts — Decision Makers, Influencers, Team Members ──
    const contacts = await Promise.all([
      // Decision Makers
      db.contact.create({
        data: {
          rawName: 'Judson Althoff',
          normalizedName: 'judson althoff',
          email: 'judson.althoff@gold-standard.example.com',
          title: 'EVP, Chief Commercial Officer',
          role: 'Executive Vice President',
          phone: '+1-425-555-0101',
          location: 'Redmond, WA',
          companyId: company.id,
          batchId: batch.id,
          leadScore: 95,
          companyFitScore: 98,
          engagementScore: 70,
          enrichmentScore: 90,
          aiConversionScore: 0.92,
          status: 'engaged',
          assignedTo: 'sarah.chen',
          source: 'manual',
          lastContactedAt: DAYS_AGO(5),
          consentStatus: 'opted_in',
          consentDate: DAYS_AGO(60),
        },
      }),
      db.contact.create({
        data: {
          rawName: 'Scott Guthrie',
          normalizedName: 'scott guthrie',
          email: 'scott.guthrie@gold-standard.example.com',
          title: 'EVP, Cloud + AI',
          role: 'Executive Vice President',
          phone: '+1-425-555-0102',
          location: 'Redmond, WA',
          companyId: company.id,
          batchId: batch.id,
          leadScore: 93,
          companyFitScore: 96,
          engagementScore: 60,
          enrichmentScore: 88,
          aiConversionScore: 0.9,
          status: 'active',
          assignedTo: 'sarah.chen',
          source: 'manual',
          lastContactedAt: DAYS_AGO(12),
          consentStatus: 'opted_in',
          consentDate: DAYS_AGO(45),
        },
      }),
      db.contact.create({
        data: {
          rawName: 'Charlie Bell',
          normalizedName: 'charlie bell',
          email: 'charlie.bell@gold-standard.example.com',
          title: 'EVP, Microsoft Security',
          role: 'Executive Vice President',
          phone: '+1-425-555-0103',
          location: 'Redmond, WA',
          companyId: company.id,
          batchId: batch.id,
          leadScore: 90,
          companyFitScore: 94,
          engagementScore: 50,
          enrichmentScore: 85,
          aiConversionScore: 0.88,
          status: 'active',
          assignedTo: 'michael.park',
          source: 'manual',
          lastContactedAt: DAYS_AGO(20),
          consentStatus: 'opted_in',
          consentDate: DAYS_AGO(30),
        },
      }),

      // Influencers
      db.contact.create({
        data: {
          rawName: 'Sarah Bodner',
          normalizedName: 'sarah bodner',
          email: 'sarah.bodner@gold-standard.example.com',
          title: 'VP, Azure AI Platform',
          role: 'Vice President',
          phone: '+1-425-555-0201',
          location: 'Redmond, WA',
          companyId: company.id,
          batchId: batch.id,
          leadScore: 85,
          companyFitScore: 92,
          engagementScore: 75,
          enrichmentScore: 82,
          aiConversionScore: 0.85,
          status: 'engaged',
          assignedTo: 'sarah.chen',
          source: 'manual',
          lastContactedAt: DAYS_AGO(3),
          consentStatus: 'opted_in',
          consentDate: DAYS_AGO(20),
        },
      }),
      db.contact.create({
        data: {
          rawName: 'Mark Russinovich',
          normalizedName: 'mark russinovich',
          email: 'mark.russinovich@gold-standard.example.com',
          title: 'CTO, Azure',
          role: 'Chief Technology Officer',
          phone: '+1-425-555-0202',
          location: 'Redmond, WA',
          companyId: company.id,
          batchId: batch.id,
          leadScore: 82,
          companyFitScore: 90,
          engagementScore: 45,
          enrichmentScore: 80,
          aiConversionScore: 0.82,
          status: 'active',
          assignedTo: 'sarah.chen',
          source: 'manual',
          lastContactedAt: DAYS_AGO(30),
          consentStatus: 'opted_in',
          consentDate: DAYS_AGO(90),
        },
      }),

      // Team Members
      db.contact.create({
        data: {
          rawName: 'Erik Weibust',
          normalizedName: 'erik weibust',
          email: 'erik.weibust@gold-standard.example.com',
          title: 'Principal Engineering Manager, Azure DevOps',
          role: 'Principal Engineer',
          phone: '+1-425-555-0301',
          location: 'Redmond, WA',
          companyId: company.id,
          batchId: batch.id,
          leadScore: 72,
          companyFitScore: 78,
          engagementScore: 80,
          enrichmentScore: 70,
          aiConversionScore: 0.7,
          status: 'active',
          assignedTo: 'alex.kim',
          source: 'manual',
          lastContactedAt: DAYS_AGO(8),
          consentStatus: 'opted_in',
          consentDate: DAYS_AGO(40),
        },
      }),
      db.contact.create({
        data: {
          rawName: 'Lina Kamat',
          normalizedName: 'lina kamat',
          email: 'lina.kamat@gold-standard.example.com',
          title: 'Director of Cloud Security Architecture',
          role: 'Director',
          phone: '+1-425-555-0302',
          location: 'Redmond, WA',
          companyId: company.id,
          batchId: batch.id,
          leadScore: 75,
          companyFitScore: 80,
          engagementScore: 55,
          enrichmentScore: 72,
          aiConversionScore: 0.73,
          status: 'active',
          assignedTo: 'michael.park',
          source: 'manual',
          lastContactedAt: DAYS_AGO(15),
          consentStatus: 'opted_in',
          consentDate: DAYS_AGO(25),
        },
      }),
    ]);

    // ── 5. Create Capability Assets — matching Microsoft signals/needs ──
    const capabilities = await Promise.all([
      db.capabilityAsset.create({
        data: {
          title: 'Cloud Migration & Modernization',
          summary: 'End-to-end cloud migration services including assessment, planning, migration execution, and optimization for Azure, AWS, and GCP environments.',
          category: 'solution',
          serviceLine: 'Cloud Services',
          technology: 'Azure',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Healthcare', 'Manufacturing']),
          businessProblem: 'Legacy system migration to cloud infrastructure, reducing technical debt while maintaining business continuity',
          customerOutcome: '60% infrastructure cost reduction, 99.99% availability, and modern DevOps practices within 6 months',
          differentiator: 'Proprietary migration factory approach with automated risk assessment and zero-downtime migration patterns',
          keywords: JSON.stringify(['cloud migration', 'azure', 'infrastructure', 'modernization', 'devops', 'kubernetes', 'container', 'terraform', 'IaC']),
          problems: JSON.stringify(['legacy system migration', 'cloud cost optimization', 'infrastructure modernization', 'container orchestration']),
          content: 'Our Cloud Migration Factory delivers predictable, accelerated cloud modernization. We combine automated assessment tools with proven migration patterns to de-risk large-scale Azure transitions.',
          isActive: true,
          upvotes: 42,
          downvotes: 2,
        },
      }),
      db.capabilityAsset.create({
        data: {
          title: 'AI & Machine Learning Platform',
          summary: 'Enterprise AI/ML platform design, implementation, and operationalization including MLOps, RAG pipelines, and generative AI deployment on Azure AI.',
          category: 'solution',
          serviceLine: 'AI & Data',
          technology: 'Azure AI',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Healthcare', 'Retail']),
          businessProblem: 'Scaling AI initiatives from proof-of-concept to production-grade systems with proper governance and monitoring',
          customerOutcome: 'Production ML systems with 95% model accuracy, sub-100ms inference latency, and automated retraining pipelines',
          differentiator: 'Azure-native MLOps framework with built-in responsible AI governance and automated model monitoring',
          keywords: JSON.stringify(['AI', 'machine learning', 'Azure AI', 'OpenAI', 'Copilot', 'RAG', 'MLOps', 'generative AI', 'GPT', 'large language models']),
          problems: JSON.stringify(['AI platform scaling', 'ML model deployment', 'RAG pipeline', 'generative AI implementation', 'AI governance']),
          content: 'End-to-end AI platform services from data engineering through model deployment and monitoring. Specialized in Azure OpenAI integration, RAG architectures, and enterprise Copilot implementations.',
          isActive: true,
          upvotes: 38,
          downvotes: 1,
        },
      }),
      db.capabilityAsset.create({
        data: {
          title: 'Cybersecurity & Zero Trust Architecture',
          summary: 'Comprehensive Zero Trust security assessment, implementation, and managed services including identity governance, threat detection, and compliance automation.',
          category: 'solution',
          serviceLine: 'Security',
          technology: 'Microsoft Defender',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Healthcare', 'Government']),
          businessProblem: 'Evolving threat landscape requiring proactive security posture, zero trust architecture, and continuous compliance monitoring',
          customerOutcome: '80% reduction in security incidents, 100% compliance posture visibility, and 24/7 threat detection with automated response',
          differentiator: 'Microsoft-native security expertise with deep Defender integration and FedRAMP/ISO certification experience',
          keywords: JSON.stringify(['cybersecurity', 'zero trust', 'security', 'Microsoft Defender', 'identity governance', 'threat detection', 'compliance', 'SOC']),
          problems: JSON.stringify(['zero trust implementation', 'security transformation', 'threat detection', 'compliance automation', 'identity governance']),
          content: 'Zero Trust architecture services built on Microsoft Defender stack. From assessment to implementation to managed SOC services, we deliver end-to-end security transformation.',
          isActive: true,
          upvotes: 35,
          downvotes: 0,
        },
      }),
      db.capabilityAsset.create({
        data: {
          title: 'Data Analytics & Business Intelligence',
          summary: 'Enterprise data platform modernization including data mesh architecture, real-time analytics, and Power BI implementation for data-driven decision making.',
          category: 'solution',
          serviceLine: 'Data & Analytics',
          technology: 'Azure Data',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Retail', 'Manufacturing']),
          businessProblem: 'Data silos and inconsistent analytics preventing enterprise-wide intelligence and real-time decision making',
          customerOutcome: 'Unified data platform with self-service analytics, 10x query performance improvement, and data-driven culture adoption',
          differentiator: 'Azure-native data mesh implementation with automated data governance and real-time streaming analytics',
          keywords: JSON.stringify(['data analytics', 'Power BI', 'data mesh', 'data platform', 'SQL Server', 'Cosmos DB', 'data engineering', 'business intelligence']),
          problems: JSON.stringify(['data silos', 'analytics modernization', 'data platform unification', 'real-time analytics', 'data governance']),
          content: 'Enterprise data platform modernization on Azure. We design and implement data mesh architectures, Power BI solutions, and real-time analytics platforms that turn data into competitive advantage.',
          isActive: true,
          upvotes: 30,
          downvotes: 1,
        },
      }),
      db.capabilityAsset.create({
        data: {
          title: 'Application Modernization',
          summary: 'Legacy application modernization using microservices, containers, and cloud-native patterns on Azure Kubernetes Service and Azure Functions.',
          category: 'solution',
          serviceLine: 'Application Services',
          technology: 'Azure',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Healthcare']),
          businessProblem: 'Monolithic applications limiting agility, scalability, and developer productivity requiring modernization to cloud-native architectures',
          customerOutcome: 'Microservices architecture with independent deployment, 4x developer productivity improvement, and 99.95% availability SLA',
          differentiator: 'Strangler fig migration pattern for zero-risk modernization with Azure Kubernetes Service expertise',
          keywords: JSON.stringify(['application modernization', 'microservices', 'Kubernetes', 'containers', 'Azure', 'cloud-native', 'Docker', 'API', 'DevOps']),
          problems: JSON.stringify(['monolithic architecture', 'application modernization', 'container orchestration', 'microservices migration', 'API strategy']),
          content: 'Systematic legacy application modernization using proven cloud-native patterns. We specialize in monolith-to-microservices transformation on Azure Kubernetes Service.',
          isActive: true,
          upvotes: 28,
          downvotes: 1,
        },
      }),
      db.capabilityAsset.create({
        data: {
          title: 'DevOps & Platform Engineering',
          summary: 'Platform engineering and DevOps transformation including CI/CD pipelines, GitOps, infrastructure-as-code, and developer experience optimization.',
          category: 'solution',
          serviceLine: 'Cloud Services',
          technology: 'Azure DevOps',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Manufacturing']),
          businessProblem: 'Slow release cycles, manual deployment processes, and developer friction reducing engineering velocity and product quality',
          customerOutcome: '10x deployment frequency, 50% reduction in lead time, and automated compliance checks in CI/CD pipelines',
          differentiator: 'Azure DevOps + GitHub Actions expertise with built-in security scanning and compliance automation',
          keywords: JSON.stringify(['DevOps', 'platform engineering', 'CI/CD', 'Terraform', 'infrastructure as code', 'GitHub Actions', 'Azure DevOps', 'GitOps']),
          problems: JSON.stringify(['slow release cycles', 'DevOps transformation', 'CI/CD automation', 'infrastructure as code', 'developer experience']),
          content: 'DevOps and platform engineering services focused on Azure. From CI/CD pipeline design to internal developer platforms, we accelerate engineering velocity.',
          isActive: true,
          upvotes: 25,
          downvotes: 0,
        },
      }),
      db.capabilityAsset.create({
        data: {
          title: 'Enterprise Integration Services',
          summary: 'Complex enterprise integration including API management, SAP/ERP cloud migration, and multi-system data integration using Azure Integration Services.',
          category: 'solution',
          serviceLine: 'Integration',
          technology: 'Azure',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Manufacturing', 'Healthcare']),
          businessProblem: 'Disconnected enterprise systems, legacy ERP platforms, and data integration complexity limiting business agility',
          customerOutcome: 'Unified enterprise integration layer with real-time data flow, SAP cloud migration, and API-first architecture',
          differentiator: 'SAP-on-Azure migration expertise with integration factory approach for repeatable enterprise patterns',
          keywords: JSON.stringify(['enterprise integration', 'SAP', 'ERP', 'API management', 'Azure Integration Services', 'data integration', 'middleware']),
          problems: JSON.stringify(['enterprise integration', 'SAP migration', 'API management', 'data integration', 'ERP modernization']),
          content: 'Enterprise integration services specializing in SAP-on-Azure migration and multi-system integration. Our integration factory approach delivers consistent, scalable results.',
          isActive: true,
          upvotes: 22,
          downvotes: 0,
        },
      }),
      db.capabilityAsset.create({
        data: {
          title: 'Digital Workplace Transformation',
          summary: 'Microsoft 365 optimization, Copilot deployment, and modern workplace strategy including adoption frameworks and change management.',
          category: 'solution',
          serviceLine: 'Productivity',
          technology: 'Microsoft 365',
          industry: 'Technology',
          targetIndustries: JSON.stringify(['Technology', 'Financial Services', 'Healthcare', 'Government']),
          businessProblem: 'Low adoption of Microsoft 365 capabilities, poor collaboration patterns, and resistance to AI-powered productivity tools',
          customerOutcome: '90% M365 adoption rate, 40% productivity improvement through Copilot, and change management framework for sustained adoption',
          differentiator: 'Microsoft 365 Copilot deployment expertise with proven adoption framework and ROI measurement',
          keywords: JSON.stringify(['Microsoft 365', 'Copilot', 'digital workplace', 'Teams', 'SharePoint', 'productivity', 'adoption', 'change management']),
          problems: JSON.stringify(['M365 adoption', 'Copilot deployment', 'digital workplace', 'productivity', 'change management']),
          content: 'Digital workplace transformation centered on Microsoft 365 and Copilot. From deployment to adoption, we ensure organizations realize the full value of their Microsoft investment.',
          isActive: true,
          upvotes: 20,
          downvotes: 0,
        },
      }),
    ]);

    // ── 6. Create Evidence entries ──
    await Promise.all([
      // Evidence for AI signal
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://azure.microsoft.com/en-us/blog/azure-ai-studio-launch',
          sourceTitle: 'Azure AI Studio Launch',
          sourceName: 'Microsoft Azure Blog',
          snippet: 'Azure AI Studio provides a unified platform for building, testing, and deploying generative AI applications with integrated OpenAI models, RAG pipelines, and enterprise-grade security controls.',
          extractedField: 'technology',
          extractedValue: 'Azure AI Studio',
          relevanceScore: 0.95,
          confidence: 0.95,
          sourceDate: DAYS_AGO(3),
          sourceQualityTier: 'premium',
        },
      }),
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://www.microsoft.com/en-us/investor',
          sourceTitle: 'Microsoft FY2025 Capital Expenditure Authorization',
          sourceName: 'Microsoft Investor Relations',
          snippet: 'The Board has authorized $10B in capital expenditure for Azure AI infrastructure expansion across 15 new data center regions, representing the largest single investment in cloud infrastructure in company history.',
          extractedField: 'funding',
          extractedValue: '$10B',
          relevanceScore: 0.98,
          confidence: 0.95,
          sourceDate: DAYS_AGO(5),
          sourceQualityTier: 'premium',
        },
      }),
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://reuters.com/technology/microsoft-restructuring',
          sourceTitle: 'Microsoft Engineering Reorganization Under New CTO',
          sourceName: 'Reuters',
          snippet: 'Satya Nadella announced a major engineering restructuring, consolidating Windows, Office, and Azure engineering under a new unified CTO structure, signaling deeper cross-product AI integration.',
          extractedField: 'leadership',
          extractedValue: 'Engineering restructuring',
          relevanceScore: 0.92,
          confidence: 0.92,
          sourceDate: DAYS_AGO(2),
          sourceQualityTier: 'premium',
        },
      }),
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://bloomberg.com/microsoft-copilot-enterprise-adoption',
          sourceTitle: 'Microsoft Copilot Reaches 60% of Fortune 500',
          sourceName: 'Bloomberg',
          snippet: 'Microsoft Copilot products have been adopted by 60% of Fortune 500 companies, with enterprise revenue from AI services growing 300% year-over-year in the most recent quarter.',
          extractedField: 'market_signal',
          extractedValue: '60% Fortune 500 adoption',
          relevanceScore: 0.88,
          confidence: 0.88,
          sourceDate: DAYS_AGO(7),
          sourceQualityTier: 'premium',
        },
      }),
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://devblogs.microsoft.com/engineering/teams-microservices',
          sourceTitle: 'Teams Architecture: From Monolith to Microservices',
          sourceName: 'Microsoft Engineering Blog',
          snippet: 'The Teams platform has completed migration from monolithic architecture to Kubernetes-based microservices, enabling independent scaling, deployment, and 3x improvement in feature delivery velocity.',
          extractedField: 'technology',
          extractedValue: 'Kubernetes microservices',
          relevanceScore: 0.9,
          confidence: 0.9,
          sourceDate: DAYS_AGO(8),
          sourceQualityTier: 'premium',
        },
      }),
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://careers.microsoft.com/us/en/jobs',
          sourceTitle: 'Microsoft Azure AI Platform Hiring Surge',
          sourceName: 'Microsoft Careers + LinkedIn',
          snippet: 'Microsoft has posted 500+ new positions for Azure AI platform team including ML engineers, AI product managers, and research scientists across Redmond, San Francisco, and London offices.',
          extractedField: 'hiring',
          extractedValue: '500+ AI engineers',
          relevanceScore: 0.85,
          confidence: 0.85,
          sourceDate: DAYS_AGO(10),
          sourceQualityTier: 'standard',
        },
      }),
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://news.sap.com/microsoft-sap-partnership',
          sourceTitle: 'Microsoft and SAP Expand Cloud ERP Partnership',
          sourceName: 'SAP News',
          snippet: 'Microsoft and SAP announced an expansion of their RISE with SAP program, targeting 500+ joint enterprise customers for ERP cloud migration within 18 months, with dedicated Azure integration.',
          extractedField: 'partnership',
          extractedValue: 'SAP-Azure ERP partnership',
          relevanceScore: 0.85,
          confidence: 0.85,
          sourceDate: DAYS_AGO(18),
          sourceQualityTier: 'premium',
        },
      }),
      db.evidence.create({
        data: {
          companyId: company.id,
          sourceUrl: 'https://gartner.com/reviews/microsoft-cloud-ai',
          sourceTitle: 'Gartner Magic Quadrant: Cloud AI Developer Services',
          sourceName: 'Gartner',
          snippet: 'Microsoft has been named a Leader in the Cloud AI Developer Services Magic Quadrant for the third consecutive year, positioned highest for ability to execute and completeness of vision.',
          extractedField: 'competitive_position',
          extractedValue: 'Gartner Leader',
          relevanceScore: 0.8,
          confidence: 0.8,
          sourceDate: DAYS_AGO(20),
          sourceQualityTier: 'premium',
        },
      }),
    ]);

    return NextResponse.json({
      success: true,
      data: {
        company: company.id,
        companyName: company.rawName,
        signals: signals.length,
        contacts: contacts.length,
        capabilities: capabilities.length,
        evidence: 8,
      },
      message: 'Gold Standard Account created. Open Microsoft Corporation in the Intelligence OS to validate.',
    });
  } catch (error) {
    console.error('[gold-standard-seed] Error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to create Gold Standard Account', details: String(error) },
      { status: 500 }
    );
  }
}
