/**
 * M5 Phase 1.5 — TRUST Metadata Framework
 *
 * Universal standard for every intelligence output in DeepMindQ.
 * Every data point, signal, recommendation, and insight must carry
 * TRUST metadata so enterprise buyers can evaluate credibility.
 *
 * TRUST = Transparency, Reliability, Understandability, Source, Traceability
 *
 * Four mandatory dimensions:
 *   1. Source    — Where did this intelligence come from?
 *   2. Confidence — How reliable is this assessment?
 *   3. Freshness  — When was this last verified?
 *   4. Reasoning  — Why did the system reach this conclusion?
 *
 * Source Classification:
 *   verified_api     — Directly from a verified external API (Clearbit, Apollo)
 *   customer_data    — Entered by the customer (CRM data, uploads)
 *   internal_document — From ingested documents (knowledge base)
 *   web_intelligence  — From web search/intelligence collection
 *   ai_inference      — Generated by AI reasoning (lowest default trust)
 *   platform_computed — Computed by platform engines (scoring, matching)
 *
 * Confidence Levels:
 *   high   — Verified from multiple sources or direct provider data
 *   medium — Estimated from signals or single-source data
 *   low    — Inferred or AI-generated without strong evidence
 *
 * Design Principles:
 *   - NEVER present AI-estimated data as verified fact
 *   - Every output must be auditable back to its source
 *   - Confidence degradation over time (freshness decay)
 *   - Composable: trust scores aggregate upward
 */

// ─── Core Types ────────────────────────────────────────────────

/** Where intelligence originated */
export type TrustSource =
  | 'verified_api'
  | 'customer_data'
  | 'internal_document'
  | 'web_intelligence'
  | 'ai_inference'
  | 'platform_computed';

/** Reliability level of the intelligence */
export type TrustConfidence = 'high' | 'medium' | 'low';

/** Verification status of the data point */
export type TrustVerificationStatus =
  | 'verified'        // Confirmed by external source
  | 'cross_referenced' // Corroborated by 2+ sources
  | 'estimated'       // Platform estimation
  | 'inferred'        // AI inference
  | 'unverified';     // No verification performed

// ─── TRUST Metadata ────────────────────────────────────────────

/**
 * The core TRUST metadata object.
 * Attached to every intelligence output in the platform.
 */
export interface TrustMetadata {
  /** Where this intelligence originated */
  source: TrustSource;

  /** Confidence level: high / medium / low */
  confidence: TrustConfidence;

  /** ISO 8601 timestamp of last verification */
  freshness: string;

  /** Human-readable explanation of why this conclusion was reached */
  reasoning: string;

  /** Optional: Specific data provider (e.g., 'clearbit', 'apollo', 'tavily') */
  provider?: string;

  /** Optional: Specific field this metadata applies to */
  field?: string;

  /** Optional: Original raw value before platform processing */
  originalValue?: string;

  /** Optional: Number of evidence sources backing this assessment */
  evidenceCount?: number;

  /** Optional: Verification status */
  verificationStatus?: TrustVerificationStatus;
}

// ─── TRUST Score ───────────────────────────────────────────────

/**
 * Aggregated TRUST score (0-100) computed from metadata dimensions.
 * Used for quick sorting, filtering, and display.
 *
 * Weighting:
 *   Source reliability:    30%
 *   Confidence level:      25%
 *   Freshness recency:    25%
 *   Evidence count:       20%
 */
export interface TrustScore {
  /** Composite score 0-100 */
  score: number;

  /** Letter grade for quick visual scanning */
  grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'F';

  /** Breakdown by dimension */
  dimensions: {
    source: number;      // 0-100
    confidence: number;  // 0-100
    freshness: number;    // 0-100
    evidence: number;    // 0-100
  };

  /** The metadata this score was computed from */
  metadata: TrustMetadata;
}

// ─── Source Reliability Scores ─────────────────────────────────

/**
 * Static reliability scores for each source type.
 * These are NOT ML-derived — they are deterministic based on source characteristics.
 */
export const SOURCE_RELIABILITY_SCORES: Record<TrustSource, number> = {
  verified_api: 95,
  customer_data: 90,
  internal_document: 85,
  web_intelligence: 70,
  platform_computed: 80,
  ai_inference: 55,
};

// ─── Consolidated Reliability Score ──────────────────────────────

/** Mapping from legacy SourceType strings to their equivalent TrustSource */
const SOURCE_TYPE_TO_TRUST_SOURCE: Record<string, TrustSource> = {
  clearbit: 'verified_api',
  apollo: 'verified_api',
  crunchbase: 'verified_api',
  csv: 'customer_data',
  excel: 'customer_data',
  document: 'internal_document',
  human: 'customer_data',
  website: 'web_intelligence',
  rss: 'web_intelligence',
};

/**
 * Get the reliability score (0-100) for a given source.
 *
 * This is the SINGLE SOURCE OF TRUTH for source reliability.
 * Accepts either a TrustSource or a legacy SourceType string.
 *
 * @param source - A TrustSource (e.g., 'verified_api') or SourceType (e.g., 'clearbit')
 * @returns Reliability score 0-100
 */
export function getReliabilityScore(source: string): number {
  // If it's a direct TrustSource, look it up
  if (source in SOURCE_RELIABILITY_SCORES) {
    return SOURCE_RELIABILITY_SCORES[source as TrustSource];
  }
  // Otherwise, map from legacy SourceType to TrustSource
  const mappedTrustSource = SOURCE_TYPE_TO_TRUST_SOURCE[source];
  if (mappedTrustSource) {
    return SOURCE_RELIABILITY_SCORES[mappedTrustSource];
  }
  // Unknown source — return lowest default
  return 55;
}

/** Human-readable labels for source types */
export const SOURCE_LABELS: Record<TrustSource, string> = {
  verified_api: 'Verified API Data',
  customer_data: 'Customer Data',
  internal_document: 'Internal Document',
  web_intelligence: 'Web Intelligence',
  platform_computed: 'Platform Computed',
  ai_inference: 'AI Inference',
};

// ─── Confidence Numeric Mapping ───────────────────────────────

export const CONFIDENCE_SCORES: Record<TrustConfidence, number> = {
  high: 90,
  medium: 65,
  low: 35,
};

// ─── TRUST Score Computation ────────────────────────────────────

/**
 * Compute a TRUST score from metadata.
 *
 * @param metadata - The TRUST metadata to score
 * @param options - Optional overrides (e.g., custom freshness baseline)
 * @returns TrustScore with composite score and dimensional breakdown
 */
export function computeTrustScore(
  metadata: TrustMetadata,
  options?: { now?: Date; maxAgeDays?: number }
): TrustScore {
  const now = options?.now || new Date();
  const maxAgeDays = options?.maxAgeDays || 90;

  // Source reliability (0-100)
  const sourceScore = SOURCE_RELIABILITY_SCORES[metadata.source];

  // Confidence level (0-100)
  const confidenceScore = CONFIDENCE_SCORES[metadata.confidence];

  // Freshness score (0-100) — decays over time
  const freshnessDate = new Date(metadata.freshness);
  const ageDays = Math.max(0, (now.getTime() - freshnessDate.getTime()) / (1000 * 60 * 60 * 24));
  const freshnessDecay = Math.max(0, 1 - (ageDays / maxAgeDays));
  const freshnessScore = Math.round(freshnessDecay * 100);

  // Evidence count score (0-100)
  const evidenceCount = metadata.evidenceCount || 1;
  const evidenceScore = Math.min(100, Math.round(50 + (evidenceCount * 10)));

  // Weighted composite
  const composite = Math.round(
    (sourceScore * 0.30) +
    (confidenceScore * 0.25) +
    (freshnessScore * 0.25) +
    (evidenceScore * 0.20)
  );

  return {
    score: composite,
    grade: scoreToGrade(composite),
    dimensions: {
      source: sourceScore,
      confidence: confidenceScore,
      freshness: freshnessScore,
      evidence: evidenceScore,
    },
    metadata,
  };
}

function scoreToGrade(score: number): TrustScore['grade'] {
  if (score >= 95) return 'A+';
  if (score >= 85) return 'A';
  if (score >= 70) return 'B';
  if (score >= 55) return 'C';
  if (score >= 40) return 'D';
  return 'F';
}

// ─── TRUST Metadata Builders ────────────────────────────────────

/**
 * Create TRUST metadata for verified API data.
 */
export function verifiedApiTrust(
  field: string,
  provider: string,
  originalValue: string,
  reasoning?: string
): TrustMetadata {
  return {
    source: 'verified_api',
    confidence: 'high',
    freshness: new Date().toISOString(),
    reasoning: reasoning || `Field "${field}" directly verified by ${provider} API.`,
    provider,
    field,
    originalValue,
    verificationStatus: 'verified',
  };
}

/**
 * Create TRUST metadata for customer-provided data.
 */
export function customerDataTrust(
  field: string,
  originalValue: string,
  reasoning?: string
): TrustMetadata {
  return {
    source: 'customer_data',
    confidence: 'high',
    freshness: new Date().toISOString(),
    reasoning: reasoning || `Field "${field}" provided directly by customer.`,
    field,
    originalValue,
    verificationStatus: 'verified',
  };
}

/**
 * Create TRUST metadata for AI-generated intelligence.
 * Always starts at 'low' or 'medium' — must earn higher confidence.
 */
export function aiInferenceTrust(
  field: string,
  reasoning: string,
  evidenceCount: number = 0,
  confidence: TrustConfidence = 'low'
): TrustMetadata {
  return {
    source: 'ai_inference',
    confidence,
    freshness: new Date().toISOString(),
    reasoning,
    field,
    evidenceCount,
    verificationStatus: evidenceCount >= 2 ? 'cross_referenced' : 'inferred',
  };
}

/**
 * Create TRUST metadata for platform-computed data (scoring, matching).
 */
export function platformComputedTrust(
  field: string,
  reasoning: string,
  evidenceCount: number = 1,
  confidence: TrustConfidence = 'medium'
): TrustMetadata {
  return {
    source: 'platform_computed',
    confidence,
    freshness: new Date().toISOString(),
    reasoning,
    field,
    evidenceCount,
    verificationStatus: evidenceCount >= 2 ? 'cross_referenced' : 'estimated',
  };
}

/**
 * Create TRUST metadata for web intelligence (search results, signals).
 */
export function webIntelligenceTrust(
  field: string,
  sourceUrl: string,
  reasoning: string,
  confidence: TrustConfidence = 'medium'
): TrustMetadata {
  return {
    source: 'web_intelligence',
    confidence,
    freshness: new Date().toISOString(),
    reasoning,
    field,
    originalValue: sourceUrl,
    verificationStatus: 'unverified',
  };
}

// ─── TRUST Aggregation ─────────────────────────────────────────

/**
 * Aggregate multiple TRUST metadata objects into a single composite.
 * Used when composing intelligence from multiple sources (e.g., WOW #1).
 *
 * Strategy: Weighted average with confidence boost for cross-referencing.
 */
export function aggregateTrust(trustItems: TrustMetadata[]): TrustMetadata {
  if (trustItems.length === 0) {
    return {
      source: 'ai_inference',
      confidence: 'low',
      freshness: new Date().toISOString(),
      reasoning: 'No trust metadata available.',
    };
  }

  if (trustItems.length === 1) {
    return trustItems[0]!;
  }

  // Count sources by type
  const sourceCounts = new Map<TrustSource, number>();
  let totalEvidence = 0;
  let newestDate = '';

  for (const item of trustItems) {
    sourceCounts.set(item.source, (sourceCounts.get(item.source) || 0) + 1);
    totalEvidence += item.evidenceCount || 1;
    if (item.freshness > newestDate) {
      newestDate = item.freshness;
    }
  }

  // Determine composite confidence
  const hasVerifiedApi = sourceCounts.has('verified_api');
  const hasCustomerData = sourceCounts.has('customer_data');
  const hasMultipleSources = sourceCounts.size >= 2;

  let compositeConfidence: TrustConfidence = 'low';
  if (hasVerifiedApi && hasCustomerData && hasMultipleSources) {
    compositeConfidence = 'high';
  } else if (hasVerifiedApi || hasCustomerData || hasMultipleSources) {
    compositeConfidence = 'medium';
  }

  // Determine primary source (highest reliability)
  const sourcePriority: TrustSource[] = [
    'verified_api', 'customer_data', 'internal_document',
    'platform_computed', 'web_intelligence', 'ai_inference',
  ];
  let primarySource: TrustSource = 'ai_inference';
  for (const s of sourcePriority) {
    if (sourceCounts.has(s)) {
      primarySource = s;
      break;
    }
  }

  return {
    source: primarySource,
    confidence: compositeConfidence,
    freshness: newestDate || new Date().toISOString(),
    reasoning: `Composite intelligence from ${trustItems.length} sources: ${Array.from(sourceCounts.entries()).map(([s, c]) => `${s}(${c})`).join(', ')}.`,
    evidenceCount: totalEvidence,
    verificationStatus: hasMultipleSources ? 'cross_referenced' : 'estimated',
  };
}

// ─── TRUST Decorator ────────────────────────────────────────────

/**
 * Wrap any data object with TRUST metadata.
 * Returns the original object with an added `_trust` field.
 *
 * Usage:
 *   const enriched = withTrust(companyData, verifiedApiTrust('employees', 'clearbit', '15420'));
 */
export function withTrust<T>(data: T, trust: TrustMetadata): T & { _trust: TrustMetadata } {
  return {
    ...data,
    _trust: trust,
  };
}

/**
 * Wrap an array of data items with their corresponding TRUST metadata.
 */
export function withTrustBatch<T>(
  items: T[],
  trusts: TrustMetadata[]
): (T & { _trust: TrustMetadata })[] {
  return items.map((item, i) => ({
    ...item,
    _trust: trusts[i] || {
      source: 'ai_inference',
      confidence: 'low',
      freshness: new Date().toISOString(),
      reasoning: 'No trust metadata available for this item.',
    },
  }));
}
